contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    #/contact/
    url(r'^$', views.contact, name='contact'),
    #/contact/sendMsg/
    url(r'^sendMsg/$', views.sendMsg),  
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
   
    url(r'^$', views.home, name='home'),
    url(r'^shl-testy/$', views.shl, name='shl'),
    url(r'^testy-talent-q/$', views.talentq, name='talent-q'),
    url(r'^ontarget-testy/$', views.ontarget, name='ontarget'),
    url(r'^kenexa/$', views.kenexa, name='kenexa'),
    url(r'^saville-assessment/$', views.saville, name='saville-assessment'),
    url(r'^test-uotsona-gleyzera/$', views.watsonglaser, name='watson-glaser'),
    url(r'^robots\.txt$', views.robotsTxt),
    url(r'^ads\.txt$', views.adsTxt),
]

iq/urls.py
from django.conf.urls import url
from . import views
from .models import Iqtest

app_name = 'iq'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='iqredirect'),
    #/shltest/791/
    url(r'^(?P<iqtest_id>[0-9]+)/$', views.iqtest_view, name='iqtest_view'),
     #/shltest/1/get_data/
    url(r'^(?P<iqtest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^(?P<iqtest_id>[0-9]+)/post_data/$', views.post_data),
]

logic/urls.py
from django.conf.urls import url
from . import views
from .models import Logictest

app_name = 'logic'

urlpatterns = [
    #/tqtest/
    url(r'^$', views.url_redirect, name='logicredirect'),
    #/tqltest/791/
    url(r'^(?P<logictest_id>[0-9]+)/$', views.logictest_view, name='logictest_view'),
     #/tqltest/1/get_data/
    url(r'^(?P<logictest_id>[0-9]+)/get_data/$', views.get_data),
     #/tqltest/1/post_data/
    url(r'^(?P<logictest_id>[0-9]+)/post_data/$', views.post_data),
]

numTests/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('chislovye-testy/', include('shlquestions.urls')),
    path('chislovye-testy/talent-q/', include('tqquestions.urls')),
    path('contact/', include('contact.urls')),
    path('logicheskiye-testy/', include('logic.urls')),
    path('inductive/', include('iq.urls')),
    path('verbalnyy-test-online/', include('verbal.urls')),

    
    path('numerical/', views.numredirect),
    path('verbal/', views.verbredirect),
    path('logical/', views.logicredirect),
    path('shl/', views.shlredirect),
    path('talent-q/', views.tqredirect),
    path('ontarget/', views.ontargetredirect),
    path('watson-glaser/', views.wgredirect),
    
]

tqquestions/urls.py
from django.conf.urls import url
from . import views
from .models import TQtest

app_name = 'tqquestions'

urlpatterns = [
    #/tqtest/
    url(r'^$', views.url_redirect, name='tqredirect'),
    #/tqltest/791/
    url(r'^(?P<tqtest_id>[0-9]+)/$', views.tqtest_view, name='tqtest_view'),
     #/tqltest/1/get_data/
    url(r'^(?P<tqtest_id>[0-9]+)/get_data/$', views.get_data),
     #/tqltest/1/post_data/
    url(r'^(?P<tqtest_id>[0-9]+)/post_data/$', views.post_data),
]

verbal/urls.py
from django.conf.urls import url
from . import views
from .models import Verbaltest

app_name = 'verbal'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='verbalredirect'),
    #/shltest/791/
    url(r'^(?P<verbaltest_id>[0-9]+)/$', views.verbaltest_view, name='verbaltest_view'),
     #/shltest/1/get_data/
    url(r'^(?P<verbaltest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^(?P<verbaltest_id>[0-9]+)/post_data/$', views.post_data),
]

tqquestions/models.py
from django.db import models

class TQtest(models.Model):
    testName = models.CharField(max_length=250)
    testCoverageStatistics = models.CharField(max_length=300)
    
    def __str__(self):
        return self.testName

class TQquest(models.Model):
    tqTest = models.ForeignKey(TQtest, on_delete=models.CASCADE,null=True)
    numInRow = models.IntegerField()
    question = models.CharField(max_length=1000)
    question_img = models.FileField(blank=True, null=True)
    rightAnswer = models.CharField(max_length=200)
    rightAnswerNum = models.IntegerField()
    answerOne = models.CharField(max_length=200)
    answerTwo = models.CharField(max_length=200)
    answerThree = models.CharField(max_length=200)
    answerFour = models.CharField(max_length=200)
    answerFive = models.CharField(max_length=200)
    answerSix = models.CharField(max_length=200)
    answerSeven = models.CharField(max_length=200)
    answerEight = models.CharField(max_length=200)
    answerNine = models.CharField(max_length=200)
    answerTen = models.CharField(max_length=200)
    
    def __str__(self):
         return str(self.numInRow)+' - '+str(self.tqTest)

tqquestions/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from tqquestions.models import TQquest, TQtest
import json
import random

def url_redirect(request):
    
   
    return redirect('/numerical/talent-q/1/')


def tqtest_view(request, tqtest_id):
    try:
        tqTest1 = TQtest.objects.get(pk=tqtest_id)
    except TQtest.DoesNotExist:
        raise Http404

    question = []
    image = []
    for i in range(1, tqTest1.tqquest_set.count()+1):
        quest1=tqTest1.tqquest_set.get(numInRow=i)
        question.append(quest1.question)
        image.append(str(quest1.question_img))
    qmlist =  zip(question, image)
    adverNum = str(random.randint(1,1))
    context = {
        'qmlist': qmlist,
        'tqtest_id': tqtest_id,
        'adverNum': adverNum,
       }
    return render(request, 'tqquestions/tq.html', context)

    #  return HttpResponse('<h1>we are in SHL '+str(shltest_id)+' test app</h1>')

def get_data(request, tqtest_id):
    if request.is_ajax():
        try:
            tqTest1 = TQtest.objects.get(pk=tqtest_id)
        except TQtest.DoesNotExist:
            raise Http404

        response_data = {}
        answers = []
        rightAnswers = []
        for i in range(1, tqTest1.tqquest_set.count()+1):
            quest1=tqTest1.tqquest_set.get(numInRow=i)
            temp = []
            temp.append(quest1.answerOne)
            temp.append(quest1.answerTwo)
            temp.append(quest1.answerThree)
            temp.append(quest1.answerFour)
            temp.append(quest1.answerFive)
            temp.append(quest1.answerSix)
            temp.append(quest1.answerSeven)
            temp.append(quest1.answerEight)
            temp.append(quest1.answerNine)
            temp.append(quest1.answerTen)
            answers.append(temp)
            rightAnswers.append(quest1.rightAnswerNum)
       
        x = tqTest1.testCoverageStatistics
        statistics = x.split(",")
        statistics = list(map(int, statistics))
        
        response_data['answers'] = answers
        response_data['rightAnswers'] = rightAnswers
        response_data['statistics'] = statistics
        return HttpResponse(json.dumps(response_data), content_type='application/json')
    else:
        raise Http404

def post_data(request, tqtest_id):
    if request.is_ajax():
        theNumber = int(request.POST.get("theNumber", ""))
        if (theNumber > 0):
            try:
                tqTest1 = TQtest.objects.get(pk=tqtest_id)
            except:
                 pass
            else:
                 statistics = []
                 x = tqTest1.testCoverageStatistics
                 statistics = x.split(",")
                 statistics = list(map(int, statistics))
                 statistics[theNumber-1] = statistics[theNumber-1]+1
                 newStatistics = ','.join(map(str, statistics)) 
                 tqTest1.testCoverageStatistics = newStatistics
                 tqTest1.save()
                 return HttpResponse('')
        else:
            return HttpResponse('')
                 # x = shlTest1.testCoverageStatistics
                 # response_data = {}
                 # response_data['someNumber'] = x
                 # return HttpResponse(json.dumps(response_data), content_type='application/json')

tqquestions/templates/tqquestions/brief.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128963188-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128963188-1');
</script>

	<meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  


	<title>Числовой тест Talent Q при приеме на работу | Бесплатные примеры тестов с ответами</title>
  <meta name="description" content="Числовые тесты Talent Q при приеме на работу. Бесплатные примеры с ответами и результатами. Советы и описания решений числовых тестов при приеме на работу."> 
  <meta name="og:title" property="og:title" content="Числовой тест Talent Q при приеме на работу | Бесплатные примеры тестов с ответами">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="Числовые тесты Talent Q при приеме на работу. Бесплатные примеры с ответами и результатами. Советы и описания решений числовых тестов при приеме на работу."/>
  <meta property="og:image" content="http://digitaltests.ru/static/home/images/ogImage.png" />
  <meta name="robots" content="index, follow"> 



	<link rel="shortcut icon" href="http://digitaltests.ru/static/home/images/d.ico">
  <link rel="stylesheet" href="{% static 'tqquestions/brief.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Oswald&amp;subset=cyrillic" rel="stylesheet"> 
 
  <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>

  <script type="text/javascript" src="{% static 'iq/brief.js' %}"></script>
  <script type="text/javascript">
    var homelbl = "{% static 'iq/images/home.png' %}";
    var home1lbl = "{% static 'iq/images/home1.png' %}";
 </script>
  
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-4181873530301054",
    enable_page_level_ads: true
  });
</script>
  
</head>
<body> 
   
   <header>
     <div class="adverTop"><center>Comercial</center></div>
    <!-- верхнее меню-->
     <nav>
       <ul class="topnav" id="myTopnav">
        <a  href="{% url 'home:home' %}"><img src="{% static 'home/images/Label.svg' %}" alt="тесты при приеме на работу" width=121px style="margin-bottom: -5px"></a>
        <a  class="navBtn" id="toptavTxt" href="{% url 'home:home' %}"><img class="home" src="{% static 'tqquestions/images/home.png' %}" alt="дом" width=22px></a>
        <a  class="navBtn" href="{% url 'shlquestions:Shlredirect' %}">SHL</a>
        <a  class="navBtnAct" href="{% url 'tqquestions:tqredirect' %}">Talent Q</a>
         <a  class="navBtn" href="{% url 'verbal:verbalredirect' %}">Вербальные</a>
        <a  class="navBtn" href="{% url 'logic:logicredirect' %}">Логические</a>
        <a  class="navBtn" href="{% url 'iq:iqredirect' %}">IQ тесты</a>
       
        <a  class="navBtn" href="{% url 'contact:contact' %}">Обратная связь</a>
        <a></a>
        <a  id="menu" class="icon"><img src="{% static 'tqquestions/images/burger.svg' %}" width=22px></a>
       </ul>
     </nav>
    </header>
    <div class="lineQ"></div>
  <main>

  	
  {% include "home/testexpert-top.html" %}

<div class="about">
   <div id="aboutTests">
      <div class="svgLable">
      <img id="aboutImg" src="{% static 'tqquestions/images/tqLabel.svg' %}" alt="числовой тест при приеме на работу">
      </div>
      <div id="textForTestAbout"><h1>Числовой тест Talent Q при приеме на работу</h1></div>
  </div>

  <div class="blueLine" ></div>
<p>Практика повышает результаты тестирования. Приготовтесь к числовому тесту Talent Q при приеме на работу, решив три бесплатных варианта. Для начала теста выберети нужный вариант и нажмите на кнопку старт на следующей странице.
</p>
  
  <h2 style="margin-top: 30px;">Инструкция к числовому тесту Talent Q</h2>
<div class="blueLine" id="grey"></div>
  <p>Числовой тест Talent Q при приеме на работу содержит 10 вопросов. На решение одного вопроса отводится ровно 60 секунд. Для решения теста рекомендуется иметь под рукой калькулятор и черновик.</p>

  <p>Для того, чтобы хорошо решить числовой тест нужно считать быстро и точно. Старайтесь ответить на все вопросы. У вас не будет возможности вернуться и изменить ответ. В каждом вопросе десять возможных вариантов ответов, из который только один правильный.</p>

  <p>Тест можно завершить в любое время. По истечении времени тест завершиться автоматически, приняв все выбранные ответы.</p>
 
 <p>Постарайтесь найти место, где вы не будете отвлекаться во время теста. Результаты числового теста Talent Q и правильные ответы будут доступны бесплатно сразу после завершения. </p>



  <div class="buttons">
      <a href="/tqtest/1/" class="button">Числовой тест 1</a>
      <a href="/tqtest/2/" class="button">Числовой тест 2</a>
      <a href="/tqtest/3/" class="button">Числовой тест 3</a>
     </div>



   
<h2>Пример решения числового теста Talent Q при приеме на работу</h2>
<div class="blueLine" id="grey"></div>
<p>В этом году расходы компании выросли на 15% и составили 690 млн, общаяя структура расходов не изменилась. Сколько составляли расходы компании на рекламу в прошлом году?</p>

<img id="testImg" src="{% static 'tqquestions/images/Quest/3-11.png' %}" alt="числовой тест при приеме на работу" style="margin-top: 20px;">

<p>Шаг 1:  Общая сумма расходов прошлого года = 690 млн / 1,15 = 600 млн.</p>

<p>Шаг 2:  Расходы на рекламу в прошлом году = 600 млн * 0,25 = 150 млн.</p>

<p>Правильный ответ: 150 млн.</p>


<h2>Советы по решению числовых тестов при приеме на работу</h2>
<div class="blueLine" id="grey"></div>
<p>1. Внимательно прочитайте или выслушайте инструкцию. Как правило, в начале числовых тестов при приеме на работу следует инструкция и несколько примеров вопросов. Уделите достаточно времени, что бы внимательно их изучить, это поможет в понимании предстоящего теста. </p>

<p>2. Игнорируйте чужие результаты. Не позволяйте себе думать о там, как быстро или медленно данные вопросы решали другие люди. Постарайтесь сконцентрироваться на том, что вы делаете. </p>

<p>3. Вопросы могут быть с подвохами. Иногда вопросы к числовым тестам составляются таким образом, что бы увести вас в ложную сторону. Остерегайтесь таких вопросов, они сделаны специально, что бы проверить вашу внимательность. </p>
</div>
<div class="lineQ2"></div>

<div class="suppurtProject">

  <div class="donate">
    <p>Поддержать проект</p>
    <div class="blueline"></div>
   <form method="POST" action="https://money.yandex.ru/quickpay/confirm.xml">

    <input type="hidden" name="receiver" value="410017817397270">

       

    <input type="hidden" name="quickpay-form" value="donate">

    <input type="hidden" name="targets" value="Digital Tests">
  
   <div class="moneyInput">

    <div class="textInput">
         <label for="id_sum">Сумма ₽</label>
         <input type="text" name="sum" id="id_sum" value="" data-type="currency">
      </div>
    <div class="wrapper">
        <div>
          <input type="radio" id="id_Ymomey" name="paymentType" value="PC">
            <label for="id_Ymomey"><img src="{% static 'home/images/yandex-money1.png' %}" id="yMoney"></label>
        </div>
        <div>
            <input type="radio" id="McVMirMoney" name="paymentType"  value="AC" checked>
             <label for="McVMirMoney"><img src="{% static 'home/images/logoVisa_Mast_Mir.png' %}" id="McVMirMoney">
             </label>
             </div>
       </div>
        
     </div>
       <input class="button sendMoney" type="submit" value="ПЕРЕВЕСТИ">
     </form>

   </div>

   <div class="greyLine" id="lastGrey"></div>
  
  <div class="adver">
   
    {% with "home/adver"|add:adverNum|add:".html" as template %}  
    {% include template %}  
    {% endwith %} 

  </div>
</div>


  </main>

  <footer>
      <img id="prefooter" src="{% static 'home/images/preGroup.png' %}">
  	<div class="footer">
   <img id="footerimg" src="{% static 'home/images/Group.png' %}" alt="тесты при приеме на работу" >
    <div class="footerRef">
        {% include "home/footerRef.html" %} 
     </div>
  </div>
   
  </footer>
   
   


</body>

</html>

tqquestions/templates/tqquestions/tq.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru-RU">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->


  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <title>Talent Q числовой тест: бесплатный вариант {{tqtest_id}}</title>
  <meta name="description" content="Talent Q числовой тест вариант {{tqtest_id}} для подготовки при приеме на работу. Пример с бесплатными ответами и результатами"> 
  
  <meta name="og:title" property="og:title" content="Talent Q числовой тест: бесплатный вариант {{tqtest_id}}">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="Talent Q числовой тест вариант {{tqtest_id}} для подготовки при приеме на работу. Пример с бесплатными ответами и результатами"/>
  <meta property="og:image" content="http://digitaltests.ru/static/home/images/ogImage.png" />
  <meta name="robots" content="index, follow"> 

   <meta property="og:url" content="https://digitaltests.ru/chislovye-testy/talent-q/{{tqtest_id}}/" />

  {% include "home/tags.html" %}


<link rel="shortcut icon" href="http://digitaltests.ru/static/home/images/d.ico">
  <link rel="stylesheet" href="{% static 'tqquestions/styleTQ.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'home/navBar.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Oswald&amp;subset=cyrillic" rel="stylesheet"> 
 
  <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript">
    var userTQTestCoverage = [0, 0, 0];
    var navBarLinkId = 1;
 </script>
  
  <script type="text/javascript" class = "dataT">
    var tqTestNT = {{tqtest_id|safe}};
    var csrftoken = '{{ csrf_token }}';
  </script>

  <script type="text/javascript" src="{% static 'tqquestions/scriptTQ.js' %}"></script>
 
<script type="text/javascript" src="{% static 'home/navBar.js' %}"></script>
  
</head>
<body> 
   
   <header>
  
     <nav>
       
     {% include "home/navBar.html" %} 

     </nav>
    </header>
<div class="lineQ" id="firstQ"></div>
  <main>

  	

    <div class="mainTestBlock">

       <div class="ctrPanel">
       
         <h1>Talent Q числовой тест {{tqtest_id}}</h1>
         <a href="/chislovye-testy/talent-q/1/"><p>Вариант 1 - 0%</p></a>
         <a href="/chislovye-testy/talent-q/2/"><p>Вариант 2 - 0%</p></a>
         <a href="/chislovye-testy/talent-q/3/"><p>Вариант 3 - 0%</p></a>
         <div class="buttons">
         <div class="button start hide">СТАРТ</div>
         <div class="button finish hide">ЗАВЕРШИТЬ</div>
          <div class="button loader ">
            <div class="spinner">
             <div class="bounce1"></div>
             <div class="bounce2"></div>
             <div class="bounce3"></div>
            </div>
         </div>
         </div>
         <div class="timer">1:00</div>
        
       </div>

       <div class="questions">
         
          <div class="tutorial ">

            <p>Внимательно прочитайте вопрос  <span><img src="{% static 'tqquestions/images/TQ/Arrow.svg' %}"></span></p>
            <p>Выберите правильный вариант ответа  <span><img src="{% static 'tqquestions/images/TQ/RadoBtn.svg' %}" style="margin-bottom: -10px"></span></p>
            <p>Переходите к следующему вопросу  <span><img src="{% static 'tqquestions/images/TQ/NextBtn.svg' %}" style="margin-bottom: -15px"></span></p>
            <p>На каждый вопрос отведена одна минута  <span><img src="{% static 'tqquestions/images/TQ/time.svg' %}" style="margin-bottom:-5px"></span></p>
            <p>Решения к тестам есть в <a href="https://vk.com/digital.tests" target="_blank">группе вконтакте.</a></p>
            </div>
         
            {% for quest, imgs in qmlist %}
               <div class="quection hide">
                 <h2>{{quest}}</h2>
                 <img src="{% static 'tqquestions/images/Quest/' %}{{imgs}}" alt="информация к числовому тесту Talent Q">
               </div>
            {% endfor %}
             
             <!-- БЛОК РЕЗУЛЬТАТОВ ТЕСТА -->

          
             <div class="results hide">
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p>Правильные ответы можно посмотреть по номеру вопроса<span><img src="{% static 'tqquestions/images/TQ/wrongNumQuest.svg' %}"></span></p>
             <p>Решения вопросов есть в нашей <a href="https://vk.com/digital.tests" target="_blank">группе вконтакте.</a></p>
          </div>
         

         <div class="numOfQuest">
<!--          <input type="radio" id="1q" name="questNum" value="1">
         <label for="1q">1</label>
 -->                 
         </div>

      </div>

    <div class="answer testAnsw" id='answerAlloc'>
        
         <p class="variant1">Варианты ответов:</p>
           <div class="hideLine1"></div>
        <div class="topWrap" id="topWrap">

         <div class="scrollWrap" id="scrollWrap">

           

         </div>
         <div class="scrollTrack" id="scrollTrack"></div>
         <div class="scrollTumb" id="scrollTumb"></div>
       </div>

        <div class="hideLine2"></div>
         <div class="button next">Next</div>
         <div class="variant2" id="variant2">Варианты ответов <span class="triangleUp"></span></div>
  
   
    </div>
    
       <div class="adverleft hide">
         
    {% with "home/adver"|add:adverNum|add:".html" as template %}  
    {% include template %}  
    {% endwith %}
       </div>
     
  </div>
<div class="theNumber"></div>
    
  </main>

  <footer>
    <img id="prefooter" src="{% static 'tqquestions/images/preGroup.png' %}">
    <div class="footer">
   <img id="footerimg" src="{% static 'tqquestions/images/Group.png' %}" alt="слайд" >
    <div class="footerRef">
       {% include "home/footerRef.html" %} 
     </div>
  </div>
   
  </footer>
   


</body>

</html>