contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    #/contact/
    url(r'^$', views.contact, name='contact'),
    #/contact/sendMsg/
    url(r'^sendMsg/$', views.sendMsg),  
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
   
    url(r'^$', views.home, name='home'),
    url(r'^shl-testy/$', views.shl, name='shl'),
    url(r'^testy-talent-q/$', views.talentq, name='talent-q'),
    url(r'^ontarget-testy/$', views.ontarget, name='ontarget'),
    url(r'^kenexa/$', views.kenexa, name='kenexa'),
    url(r'^saville-assessment/$', views.saville, name='saville-assessment'),
    url(r'^test-uotsona-gleyzera/$', views.watsonglaser, name='watson-glaser'),
    url(r'^robots\.txt$', views.robotsTxt),
    url(r'^ads\.txt$', views.adsTxt),
]

iq/urls.py
from django.conf.urls import url
from . import views
from .models import Iqtest

app_name = 'iq'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='iqredirect'),
    #/shltest/791/
    url(r'^(?P<iqtest_id>[0-9]+)/$', views.iqtest_view, name='iqtest_view'),
     #/shltest/1/get_data/
    url(r'^(?P<iqtest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^(?P<iqtest_id>[0-9]+)/post_data/$', views.post_data),
]

logic/urls.py
from django.conf.urls import url
from . import views
from .models import Logictest

app_name = 'logic'

urlpatterns = [
    #/tqtest/
    url(r'^$', views.url_redirect, name='logicredirect'),
    #/tqltest/791/
    url(r'^(?P<logictest_id>[0-9]+)/$', views.logictest_view, name='logictest_view'),
     #/tqltest/1/get_data/
    url(r'^(?P<logictest_id>[0-9]+)/get_data/$', views.get_data),
     #/tqltest/1/post_data/
    url(r'^(?P<logictest_id>[0-9]+)/post_data/$', views.post_data),
]

numTests/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('chislovye-testy/', include('shlquestions.urls')),
    path('chislovye-testy/talent-q/', include('tqquestions.urls')),
    path('contact/', include('contact.urls')),
    path('logicheskiye-testy/', include('logic.urls')),
    path('inductive/', include('iq.urls')),
    path('verbalnyy-test-online/', include('verbal.urls')),

    
    path('numerical/', views.numredirect),
    path('verbal/', views.verbredirect),
    path('logical/', views.logicredirect),
    path('shl/', views.shlredirect),
    path('talent-q/', views.tqredirect),
    path('ontarget/', views.ontargetredirect),
    path('watson-glaser/', views.wgredirect),
    
]

shlquestions/urls.py
from django.conf.urls import url
from . import views
from .models import Shltest


app_name = 'shlquestions'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='Shlredirect'),
    #/shltest/791/
    url(r'^shl/(?P<shltest_id>[0-9]+)/$', views.shltest_view, name='shltest_view'),
     #/shltest/1/get_data/
    url(r'^shl/(?P<shltest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^shl/(?P<shltest_id>[0-9]+)/post_data/$', views.post_data),

    
]

verbal/urls.py
from django.conf.urls import url
from . import views
from .models import Verbaltest

app_name = 'verbal'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='verbalredirect'),
    #/shltest/791/
    url(r'^(?P<verbaltest_id>[0-9]+)/$', views.verbaltest_view, name='verbaltest_view'),
     #/shltest/1/get_data/
    url(r'^(?P<verbaltest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^(?P<verbaltest_id>[0-9]+)/post_data/$', views.post_data),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import random


# Create your views here.
def home(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/home.html', context)

def shl(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/shl.html', context)

def talentq(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/talentq.html', context)

def ontarget(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/ontarget.html', context)

def kenexa(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/kenexa2.html', context)

def saville(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/saville.html', context)


def watsonglaser(request):

   adverNum = str(random.randint(3,3))
   context = {
        'adverNum': adverNum,
       }
   return render(request, 'home/watsonglaser.html', context)



def robotsTxt(request):
   return render(request, 'home/robots.txt', content_type='text/plain')

def adsTxt(request):
   return render(request, 'home/ads.txt', content_type='text/plain')

home/templates/home/adver1.html
 {% load staticfiles %}


<div class="testexpert-body">

<div class="tei-high">
<!-- <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<!-- aftertest -->
<!-- <ins class="adsbygoogle"
     style="display:inline-block;width:234px;height:360px"
     data-ad-client="ca-pub-4181873530301054"
     data-ad-slot="5458189163"></ins>
<script>
       $(document).ready(function(){(adsbygoogle = window.adsbygoogle || []).push({})})
</script>  --> 

    <a class="testExpert" onClick="redirect_aftertest()"
        target="_blank">
        <img class="tei-high"  src="{% static 'home/images/240-dlya-poiska1.jpg' %}">
     </a>


</div>

</div>



<style type="text/css">
  .unit2{
    /*width: 320px;*/
   /* border: 1px solid red;*/
   width: 240px;
  height: 400px;
  }

.testexpert-body{
  display: flex;
  margin-left: auto;
  margin-right: auto;
  margin-top: 20px;
  cursor: pointer;
  /*width:100%;*/
  width: 234px;
  height: 360px;
 
}
.testexpert-body a{
     display: flex;
      margin-left: auto;
     margin-right: auto;
   }

.testexpert-body.wide{
  display: none;
}

 .testexpert-body .tei-wide{
  display: none;
 }

  .testexpert-body .tei-high{
 margin-left: 0px;
 }
/*
 @media screen and (max-width: 800px){

.testexpert-body.high{
  display: none;
}
.testexpert-body.wide{
  display: flex;
}
  .testexpert-body .tei-high{
     display: none;
   }
    .testexpert-body .tei-wide{
  display: flex;
  width: 100%;
 }

}
*/
</style>


  <script type="text/javascript">

    function redirect_aftertest()
    {
       ga('send', 'event', 'testexpert-aftertest', 'click');

    var win = window.open('https://test-expert.pro/?utm_source=digitaltests&utm_medium=referral&utm_campaign=digitaltestsbanner', '_blank');
  win.focus();
    }
  </script>

home/templates/home/aurora-body.html
{% load staticfiles %}

<div class="aurora-wide">
  
<!-- <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<!-- underNav -->
<!-- <ins class="adsbygoogle unit1"
     style="display:block"
     data-ad-client="ca-pub-4181873530301054"
     data-ad-slot="7238901044"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script> 
       $(document).ready(function(){(adsbygoogle = window.adsbygoogle || []).push({})})
</script>-->



  <a class="aurora-a" href="https://aurorafin.tech/ru/" 
  onClick="redirect_aurora_body()" target="_blank">
        <img class="aurora-img" src="{% static 'home/images/auroraAdver200.jpg' %}">
        <img class="aurora-img-mob" src="{% static 'home/images/auroraAdver200.jpg' %}">
  </a>
</div>





<style type="text/css"> 

.aurora-wide{
  margin-top: 40px;
  width: 100%;
}

.aurora-wide:hover{
  cursor: pointer;
}
.aurora-a{
  width: 100%;
}
.aurora-img{
  display: none;
  width: 100%;
}

.aurora-img-mob{
  display: block;
  width: 100%;
}

.aurora-p{
  color: black;
  font-size: 8px;
}




  @media screen and (max-width: 800px){

     .aurora-img{
      display: block;
      width: 100%;
    }

    .aurora-img-mob{
      display: none;
      width: 100%;
    }

  }

</style>


  <script type="text/javascript">

    function redirect_aurora_body()
    {
       ga('send', 'event', 'aurora-body', 'click2');

    }
  </script> 

home/templates/home/boxRef.html
 <h5>Возможно, вам будут интересны следующие тесты:</h5>
   <ol>
        <li><a  href="{% url 'shlquestions:Shlredirect' %}">Числовые тесты</a></li>
        <li><a  href="{% url 'verbal:verbalredirect' %}">Вербальные тесты</a></li>
        <li> <a  href="{% url 'logic:logicredirect' %}">Логические тесты</a></li>
        <li> <a  href="{% url 'iq:iqredirect' %}">Индуктивные тесты</a></li>
        
   </ol>




    

home/templates/home/compRef.html
 <h5>Компании разработчики тестов способностей:</h5>
   <ol>
        <li><a  href="{% url 'home:shl' %}">SHL</a></li>
        <li> <a  href="{% url 'home:talent-q' %}">Talent Q</a></li>
        <li> <a  href="{% url 'home:ontarget' %}">Ontarget</a></li>
        <li> <a  href="{% url 'home:kenexa' %}">Kenexa</a></li>
        <li><a  href="{% url 'home:saville-assessment' %}">Saville Assessment</a></li>
        
        <li> <a  href="{% url 'home:watson-glaser' %}">Watson Glaser</a></li>
         
       





   </ol>




    

home/templates/home/footerRef.html
 {% load staticfiles %}

 <a  href="{% url 'home:home' %}"><img src="{% static 'home/images/LabelW-2.svg' %}" alt="DigitalTests" width=121px></a>
        <a  href="{% url 'shlquestions:Shlredirect' %}">Числовые тесты</a>
        <a  href="{% url 'verbal:verbalredirect' %}">Вербальные тесты</a>
        <a  href="{% url 'logic:logicredirect' %}">Тесты на логику</a>
        <a  href="{% url 'iq:iqredirect' %}">Индуктивные тесты</a>
<div style="display: flex;">
        <a  href="{% url 'home:shl' %}">SHL</a>
         <a href="{% url 'home:talent-q' %}"  style="margin-left: 20px;                     margin-right: 20px;">Talent Q</a>
          <a class="navBtn" href="{% url 'home:ontarget' %}">Ontarget</a>
</div>
        <a  href="{% url 'contact:contact' %}">Обратная связь</a>
         <div style="width: 100%;
                    display: flex;
                    margin-top: 5px;">
            <a href="https://vk.com/digital.tests"><img src="{% static 'home/images/vk1.svg' %}" style="width: 25px;"></a>
            <a href="https://web.facebook.com/Digital-Tests-2227469264242367/"><img src="{% static 'home/images/fb1.svg' %}" 
              style="margin-left: 20px;
                     margin-right: 20px;
                     width: 25px;
              "></a>
            <a href="https://ok.ru/group/55334614532198"><img src="{% static 'home/images/ok1.svg' %}" style="width: 25px;"></a>  
        </div>

home/templates/home/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru-RU">

<head>

  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Тесты при приеме на работу онлайн примеры с ответами – на DigitalTests</title>
  <meta name="description" content="Бесплатные тесты для онлайн подготовки при устройстве на работу, примеры максимально похожи на тесты SHL, Talent Q, Ontarget и другие тесты, применяемые при приеме на работу в МВД, ФСБ, Сбербанк и другие компании."> 
  <meta name="og:title" property="og:title" content="Тесты при приеме на работу онлайн примеры с ответами – на DigitalTests">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="Бесплатные тесты для онлайн подготовки при устройстве на работу, примеры максимально похожи на тесты SHL, Talent Q, Ontarget и другие тесты, применяемые при приеме на работу в МВД, ФСБ, Сбербанк и другие компании."/>
  <meta property="og:image" content="http://digitaltests.ru/static/home/images/ogImage.png" />
 
  <meta property="og:url" content="https://digitaltests.ru/" />

  <meta name="keywords" content="тесты при приеме на работу, психологические тесты, тест бухгалтер, вербальный тест, числовой тест, тест shl">

  <meta name="robots" content="index, follow"> 

  {% include "home/tags.html" %}

  <meta name="welcomepartners" content="verification"/>

	
  <link rel="stylesheet" href="{% static 'home/home.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'home/navBar.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Oswald&amp;subset=cyrillic" rel="stylesheet"> 
 
  <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>

  <script type="text/javascript" src="{% static 'home/home.js' %}"></script>
  <script type="text/javascript" src="{% static 'home/navBar.js' %}"></script>
  <script type="text/javascript">
   var navBarLinkId = 0;
 
 </script>
  
</head>
<body> 
   
   <header>
   
    <!-- верхнее меню-->
     <nav>
       {% include "home/navBar.html" %} 
     </nav>
    </header>
      <div class="lineQ" id="firstQ"></div>
    
  <main>

{% include "home/testexpert-top.html" %}

  	<div class="banner">
       <img id="preslise" src="{% static 'home/images/preBanner.png' %}">
      <div class="imgWrapp">
     <img src="{% static 'home/images/newBanner.png' %}" alt="Банер для сайта DigitalTests">
    <div class="bannerText">

<div id="bannerWrap">
     <h1>Решайте тесты при приеме на работу вместе с DigitalTests</h1>
    
    <div id="btnFlex">

      <div class="btnBlock">
      <a href="{% url 'shlquestions:Shlredirect' %}" class="button goShl goShl2">Числовой тест</a>
    
      <a href="{% url 'verbal:verbalredirect' %}" class="button goShl goShl2">Вербальный тест</a>
      </div>

      <div class="btnBlock" id="btnBloc2">
      <a href="{% url 'logic:logicredirect' %}" class="button goShl goShl2">Логический тест</a>
       <a href="{% url 'iq:iqredirect' %}" class="button goShl goShl2">Индуктивный тест</a>
      </div>

   </div> 
</div>
     </div>
     </div> 

    </div>

 

  <div class="startPoint">
      <div class="svgLable">
      <img src="{% static 'home/images/person-in-front-of-the-world-grid-inside-a-circle-svgrepo-com.svg' %}" alt="планета">
      </div>
      <div class="textForSvg"><p>Ведущие компании требуют от соискателей наличия определенных личностных, психологических, умственных и деловых качеств. Тестирование при приеме на работу используют такие организации как ФСБ, МВД, Банки (Сбербанк, ВТБ, Альфа-Банк), крупные корпорации (Роснефть, Газпром) и различные компании (Пятерочка, МТС).</p></div>
  </div>

  <div class="startPoint" id="startPoint2">
      <div class="svgLable">
      <img src="{% static 'home/images/man-with-solutions-svgrepo-com.svg' %}" alt="путь к успеху">
      </div>
      <div class="textForSvg"><p>Тесты, используемые при приеме на работу, могут применяться для экономистов,  для бухгалтера, для юриста и менеджера, их использование зависит от работодателя, а результат может использоваться как для отбора кандидатов, так и для совокупной оценки.</p></div>
  </div>

  <div class="startPoint">
      <div class="svgLable">
      <img src="{% static 'home/images/shake-hands-svgrepo-com.png' %}" alt="рукопожатие">
      </div>
      <div class="textForSvg"><p>На сайте DigitalTests есть настоящие бесплатные тесты для онлайн подготовки при устройстве на работу, максимально похожие на тесты SHL, Talent Q, Ontarget и другие тесты, применяемые при приеме на работу сотрудников в различные компании и организации.</p></div>
  </div>

  <div class="lineQ2 lineQ3" ></div>

<div class="testDescription">


<div class="about2">
   <div class="startPoint" id="aboutTests2">
      <div class="svgLable2">
      <img  src="{% static 'home/images/shlLabel.svg' %}" alt="числовые тесты при приеме на работу">
      </div>
      <div class="textForSvg2" id="textForTestAbout2">
        <h2>Числовые тесты</h2>
      </div>
  </div>
</div>



<p><strong>Числовой тест при приеме на работу</strong> бухгалтера или экономиста позволит определить способности кандидата к анализу информации, представленной в виде таблиц, графиков и диаграмм.  </p>


</div>
   <div class="greyLine"></div>

<div class='buclet'>

  <div class="leftSideB">

    <p>Вопросы тестов зависят от компании. Например, при приеме в Сбербанк они будут содержать задания на расчет процентов, дисконтирования и  ставок.</p>
    
    <a href="{% url 'shlquestions:Shlredirect' %}" class="button goShl">Числовой тест</a>
    
  </div>

  <div class="rightSideB">
     <img src="{% static 'home/images/startup-593327_960_720.jpg' %}" alt="ноутбук, черновик, ручка">
    <p>Числовые тесты отличаются от математических тестов тем, что они не требуют знания специальных формул и сложных вычислений, а вся необходимая информация для решения содержится в вопросе.</p>
   
  </div>

</div>



<div class="lineQ2 lineQ3"></div>

<div class="testDescription">

<div class="about2">
   <div class="startPoint" id="aboutTests2">
      <div class="svgLable2">
      <img  src="{% static 'home/images/verbalLabel.svg' %}" alt="вербальные тесты при приеме на работу">
      </div>
      <div class="textForSvg2" id="textForTestAbout2">
        <h2>Вербальные тесты</h2>
      </div>
  </div>
</div>




<p>Вербальный тест широко используется при приеме юристов и адвокатов, поскольку позволяет оценить навыки работы с текстовой информацией, умения отличать факты от предположений и способности критического мышления кандидата.</p>
</div>

 <div class="greyLine"></div>
<div class='buclet'>

  <div class="leftSideB">
    
    <p>Обычно правила работы с тестом заключаются в анализе отрывка текста и оценке ложности или правдивости утверждения относительно него. Такой тест позволяет объективно оценить навыки человека независимо от его культуры и традиций.</p>
    
    <a href="{% url 'verbal:verbalredirect' %}" class="button goShl">Вербальный тест</a>
    
  </div>

  <div class="rightSideB">
     <img src="{% static 'home/images/agreement-application-business-893894.jpg' %}" alt="юридический документ, очки, компьютер">
    <p><strong>Вербальный тест при приеме на работу</strong> позволит определить, как хорошо кандидат понимает законы и прочие юридические акты.</p>
   
  </div>

</div>



<div class="lineQ2 lineQ3"></div>
 <h2 id="plusH2">Преимущества при подготовке к тестам с DigitalTests:</h2>

<div class="plussesWrap">
<div class="plusses">

  
  <div class="diamond">
    <img src="{% static 'home/images/diamond-svgrepo-com.svg' %}" alt="Бриллиант">
    <p>Лучшие бесплатные тесты на одном сайте</p>
  </div>
 
 <div class="diamond" id="centralDim" alt="Отличная оценка">
    <img src="{% static 'home/images/rightanswers.svg' %}">
    <p>Тесты с ответами сразу и без рекламы </p>
  </div>
  
  <div class="diamond" alt="Информативный буклет">
    
    <img src="{% static 'home/images/marknout.svg' %}">
    <p>Доступны онлайн с любого устройства</p>
  </div>

</div>

</div>

<div class="lineQ2 lineQ3"></div>


<div class="testDescription">

<div class="about2">
   <div class="startPoint" id="aboutTests2">
      <div class="svgLable2">
      <img  src="{% static 'home/images/logicLabel.svg' %}" alt="Логическая последовательность элементов">
      </div>
      <div class="textForSvg2" id="textForTestAbout2">
        <h2>Логические тесты</h2>
      </div>
  </div>
</div>




<p>Тесты на логику используются для отбора кандидатов на работу требующую навыков и умений находить решения и справляется с задачами, содержащими новую информацию и незнакомые условия.</p>
</div>

 <div class="greyLine"></div>
<div class='buclet'>

  <div class="leftSideB">
   
    <p>Как правило, тесты состоят из фигур, выстроенных в логической последовательности, в которой один из элементов пропущен. Чтобы его определить, нужно понять какой логике подчиняются фигуры. </p>
    
    <a href="{% url 'logic:logicredirect' %}" class="button goShl">Логический тест</a>
    
  </div>

  <div class="rightSideB">
     <img src="{% static 'home/images/tech-wallpaper-2.jpg' %}" alt="глубина">
    <p>Логические тесты часто используются для оценки навыков программистов, инженеров, технических работников и дизайнеров. </p>
   
  </div>

</div>

<div class="lineQ2 lineQ3"></div>

<div class="testDescription">

<div class="about2">
   <div class="startPoint" id="aboutTests2">
      <div class="svgLable2">
      <img  src="{% static 'home/images/iqLabel.svg' %}" alt="мудрость">
      </div>
      <div class="textForSvg2" id="textForTestAbout2">
        <h2>Индуктивные тесты</h2>
      </div>
  </div>
</div>



<p>Тесты на индуктивное мышление направлены на исследование способностей человека приходить к общим выводам основываясь на частных суждениях и закономерностях.</p>
</div>

 <div class="greyLine"></div>
<div class='buclet'>

  <div class="leftSideB">
    
    <p>Индуктивное мышление широко используется для решения различных проблем и поэтому служит важным критерием отбора на позиции, где от кандидата требуются способности самостоятельного принятия правильных решений.</p>
    
    <a href="{% url 'iq:iqredirect' %}" class="button goShl">Индуктивный тест</a>
    
  </div>

  <div class="rightSideB">
     <img src="{% static 'home/images/free_business-wallpaper-1920x1200.jpg' %}" alt="успех, рост">
    <p>Тесты на индуктивное мышление используются на собеседовании при приеме на работу в ФСБ, МВД, а так же на позиции с высоким уровнем ответственности.</p>
   
  </div>

</div>

<div class="lineQ2 lineQ3"></div>

 <h2 id="plusH2">Статистическая оценка результатов тестов</h2>
<div class="statistics">
  <div class="statDescription">
  
    <p>Пройдя тест на сайте DigitalTest, вам будет доступна статистика вашего результата относительно результатов других участников. Наиболее популярные тесты, применяемые для отбора кандидатов:</p>
    
    <img src="{% static 'home/images/statisticsMonitor.svg' %}">
    
    <div class="buttons">
      <a href="{% url 'shlquestions:Shlredirect' %}" class="button goShl" id="shlbutton">Числовой тест</a>
      <a href="{% url 'verbal:verbalredirect' %}" class="button goShl">Вербальный тест</a>
    </div>
  
  </div>

</div>

<div class="lineQ2 lineQ3"></div>


<h2 id="plusH2" >Компании разработчики тестов способностей</h2>

<div class="developers">

 <div class="devWrap">

   <p>Компании, занимающие лидирующие позиции на рынке консалтинговых услуг по оценке персонала, разрабатывающие тесты и личностные опросники. Вы, скорее всего, столкнетесь с их <em>тестами на собеседовании при приеме на работу</em>:</p>

   <div class="centerdWrap">
      
   <div class="layoutChange">
      <div class="buttons devButtons" id="firstGrid">
        <a  href="{% url 'home:shl' %}" class="button goShl">SHL</a>
        <a  href="{% url 'home:talent-q' %}" class="button goShl" id="centralButtons">Talent Q</a>
        <a  href="{% url 'home:ontarget' %}" class="button goShl">Ontarget</a>
        </div>
      
      <div class="buttons devButtons">
        <a  href="{% url 'home:kenexa' %}" class="button goShl">Kenexa</a>
        <a  href="{% url 'home:saville-assessment' %}" class="button goShl" id="centralButtons">Saville Assessment</a>
        <a  href="{% url 'home:watson-glaser' %}" class="button goShl">Watson Glaser</a>
        </div>
   </div>
      
   </div>
      
 </div>

</div>

<div class="lineQ2"></div>

<div class="suppurtProject">

   {% include "home/testexpert-foot.html" %}

</div>


  </main>

  <footer>
      <img id="prefooter" src="{% static 'home/images/preGroup.png' %}">
  	<div class="footer">
   <img id="footerimg" src="{% static 'home/images/Group.png' %}" alt="тесты при приеме на работу" >
    <div class="footerRef">
          {% include "home/footerRef.html" %} 
     </div>
  </div>
   
  </footer>
   
   


</body>

</html>

home/templates/home/navBar.html
  {% load staticfiles %}

    <div class="nawWrap">
    <ul class="topnav" id="myTopnav">

        <div class="topnav1">
            <a  href="{% url 'home:home' %}"><img src="{% static 'home/images/Label-2.svg' %}" alt="DigitalTests" width=121px style="margin-bottom: -5px"></a>
            <a  class="navBtn" href="{% url 'shlquestions:Shlredirect' %}">Числовые</a>
            <a  class="navBtn" href="{% url 'verbal:verbalredirect' %}">Вербальные</a>
            <a  class="navBtn" href="{% url 'logic:logicredirect' %}">Логические</a>
            <a  class="navBtn" href="{% url 'iq:iqredirect' %}">Индуктивные</a>
            <a  class="navBtn" href="{% url 'contact:contact' %}">Обратная связь</a>

            <div class="topSelector">
             <div class="arrow-nav"></div>
             <div class="more">Еще</div> 
            </div>
       </div>

       <div class="topnav2">
         <div class="additionalWrap">
           <a  class="navBtn" href="{% url 'home:shl' %}">SHL</a>
           <a class="navBtn" href="{% url 'home:talent-q' %}">Talent Q</a>
           <a class="navBtn" href="{% url 'home:ontarget' %}">Ontarget</a>
           <a class="navBtn" href="{% url 'home:kenexa' %}">Kenexa</a>
           <a class="navBtn" href="{% url 'home:saville-assessment' %}">Saville Assessment</a>
           <a class="navBtn" href="{% url 'home:watson-glaser' %}">Watson Glaser</a>
         </div>
       </div>

        <div  id="menu" class="icon"><img src="{% static 'verbal/images/burger.svg' %}" width=22px></div>
    </ul>
    </div>

home/templates/home/testexpert-foot.html
{% load staticfiles %}




<style type="text/css">

  .banner-foot{
    width: 100%;
    display: block;
    margin-left: auto;
    margin-right: auto;
    cursor: pointer;
    /*adsense set*/
    margin-top: 40px;
    /*border: 1px solid black;*/    
  }

  .gadver1{ 
   /* overflow: hidden;*/
    width: 100%;
    /*border: 1px solid red;*/
    height: 400px;
    margin-left: auto;
    margin-left: auto;
  }

}

}

</style>




<!--<div class="banner-foot">


  <div class="gadver1">
    <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-4181873530301054"
       data-ad-slot="2595011628"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  </div>


<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
 
</div>-->