contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    #/contact/
    url(r'^$', views.contact, name='contact'),
    #/contact/sendMsg/
    url(r'^sendMsg/$', views.sendMsg),  
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
   
    url(r'^$', views.home, name='home'),
    url(r'^shl-testy/$', views.shl, name='shl'),
    url(r'^testy-talent-q/$', views.talentq, name='talent-q'),
    url(r'^ontarget-testy/$', views.ontarget, name='ontarget'),
    url(r'^kenexa/$', views.kenexa, name='kenexa'),
    url(r'^saville-assessment/$', views.saville, name='saville-assessment'),
    url(r'^test-uotsona-gleyzera/$', views.watsonglaser, name='watson-glaser'),
    url(r'^robots\.txt$', views.robotsTxt),
    url(r'^ads\.txt$', views.adsTxt),
]

iq/urls.py
from django.conf.urls import url
from . import views
from .models import Iqtest

app_name = 'iq'

urlpatterns = [
    #/shltest/
    url(r'^$', views.url_redirect, name='iqredirect'),
    #/shltest/791/
    url(r'^(?P<iqtest_id>[0-9]+)/$', views.iqtest_view, name='iqtest_view'),
     #/shltest/1/get_data/
    url(r'^(?P<iqtest_id>[0-9]+)/get_data/$', views.get_data),
     #/shltest/1/post_data/
    url(r'^(?P<iqtest_id>[0-9]+)/post_data/$', views.post_data),
]

numTests/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('chislovye-testy/', include('shlquestions.urls')),
    path('chislovye-testy/talent-q/', include('tqquestions.urls')),
    path('contact/', include('contact.urls')),
    path('logicheskiye-testy/', include('logic.urls')),
    path('inductive/', include('iq.urls')),
    path('verbalnyy-test-online/', include('verbal.urls')),

    
    path('numerical/', views.numredirect),
    path('verbal/', views.verbredirect),
    path('logical/', views.logicredirect),
    path('shl/', views.shlredirect),
    path('talent-q/', views.tqredirect),
    path('ontarget/', views.ontargetredirect),
    path('watson-glaser/', views.wgredirect),
    
]

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label = "Имя *")
    email = forms.EmailField(label = "E-mail *")
    category = forms.ChoiceField(choices=[('quest', 'Question'),('othe', 'Others')], label = "Тип запроса (выберите) *")
    subject = forms.CharField(required = False)
    body = forms.CharField(widget = forms.Textarea)

contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ContactForm
import json
import requests
from django.core.mail import send_mail
import random
def contact(request):
    #  form = ContactForm()

    # if request.method == 'POST':
    #     email = request.POST.get("email", "")
    #     print(email)
    adverNum = str(random.randint(2,3))
    context = {
        'adverNum': adverNum,
       }

    return render(request, 'contact/contact.html', context)


def sendMsg(request):
    if request.is_ajax():
        mailsuccess = False
        response_data = {}
        recaptcha_response = request.POST.get('recaptchaResponse')
        name = request.POST.get('name')
        emai = request.POST.get('emai')
        category = request.POST.get('category')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        data = {
                'secret': '6Lc0TXYUAAAAAIWlUEhr96jFJtOBBYveADBr1LrC',
                'response': recaptcha_response,
            }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()
        if result['success']:
            try:
                send_mail((category+': '+subject), message+'\n'+'\n'+name+' '+emai, 'bot@digitaltests.ru', ['admin@digitaltests.ru']) 
            except:
                response_data['mailsuccess'] = mailsuccess
                return HttpResponse(json.dumps(response_data), content_type='application/json')
            else: 
                mailsuccess = True
                response_data['mailsuccess'] = mailsuccess
                return HttpResponse(json.dumps(response_data), content_type='application/json')
        else:
            response_data['mailsuccess'] = mailsuccess
            return HttpResponse(json.dumps(response_data), content_type='application/json')    

contact/templates/contact/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru-RU">


<head>


	<meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <title>DigitalTests - Обратная связь</title>
  <meta name="description" content="Форма обратной связи с администрацией портала DigitalTests"> 
  
  <meta name="og:title" property="og:title" content="DigitalTests - Обратная связь">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="Форма обратной связи с администрацией портала DigitalTests"/>
  <meta property="og:image" content="http://digitaltests.ru/static/home/images/ogImage.png" />
 <meta property="og:url" content="https://digitaltests.ru/contact/" />

<meta name="robots" content="index, follow"> 
  {% include "home/tags.html" %}

  <link rel="stylesheet" href="{% static 'contact/contact.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'home/navBar.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Oswald&amp;subset=cyrillic" rel="stylesheet"> 
 
  <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript">
    var csrftoken = '{{ csrf_token }}';
     var navBarLinkId = 5;
  </script>
  <script type="text/javascript" src="{% static 'contact/contact.js' %}"></script>
  <script type="text/javascript" src="{% static 'home/navBar.js' %}"></script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
   

   
</head>
<body> 
   
   <header>
     <div class="adverTop"><center>Comercial</center></div>
    <!-- верхнее меню-->
     <nav>
       {% include "home/navBar.html" %} 
     </nav>
    </header>
<div class="lineQ" id="firstQ"></div>
  <main>

  	
<div class="mainContact">

	<div class="adverBlock" style="margin-top: 30px;">

    <div class="testexpert-body wide">
    {% include "home/testexpert-body.html" %}
</div>
	  <div class="testexpert-body high">
    {% include "home/testexpert-body.html" %}
  </div>

   <div class="greyLine"></div>
   <div class="adver"> 
   {% with "home/adver"|add:adverNum|add:".html" as template %}  
    {% include template %}  
    {% endwith %} 
   </div>
   <div class="lineQ2"></div>  

	</div>
	
	<div class="feedback">
		<p>Feedback</p>
		<div class="blueline"></div>
        <div class="customForm">
        <label for="id_name">Имя * </label><span class="inputMessage" id="name"><p> - не должно быть пустым</p> <p> - только буквы и числа</p> </span>
        <input type="text" name="fname" id="id_name" placeholder="Ваше имя..">
        
        <label for="id_email">E-mail *</label><span class="inputMessage" id="email"><p> - не должно быть пустым</p> <p> - адрес не действителен</p> </span>
        <input type="text" name="femail" id="id_email" placeholder="Ваш E-mail..">

        <label for="category">Тип запроса (выберите) *</label>
        <span class="inputMessage" id="category">
        	<p> - не должно быть пустым</p> </span>
         <select id="id_category" name="category">
          <option style="display:none"></option>
          <option value="Нашли ошибку">Нашли ошибку</option>
          <option value="Размещение рекламы">Размещение рекламы</option>
          <option value="Разработка сайтов">Разработка сайтов</option>
          <option value="Другое">Другое</option>
         </select>

        <label for="id_subject">Тема *</label><span class="inputMessage" id="subject"><p> - не должно быть пустым</p> <p> - превышена максимальная длинна</p> </span>
        <input type="text" name="fsubject" id="id_subject" placeholder="Тема..">
        
        <label for="id_message">Сообщение *</label><span class="inputMessage" id="message"><p> - не должно быть пустым</p> <p> - превышена максимальная длинна</p> </span>
        <textarea id="id_message" name="message" placeholder="Ваше сообщение.." style="height:200px"></textarea>
        <div class="recaptcha1"><span class="hide">*Invalid reCAPTCHA</span></div> 
        <div class="g-recaptcha" data-sitekey="6Lc0TXYUAAAAAFeUu_3y1NgDZ2JfI6vpye85kYrX"></div>
       
        
        <div class="buttons">
         <div class="button send ">ОТПРАВИТЬ</div>
         <div class="button loader hide">
            <div class="spinner">
             <div class="bounce1"></div>
             <div class="bounce2"></div>
             <div class="bounce3"></div>
            </div>
         </div>
         </div>

      <div class="respRes hide">*Сообщение не отправлено, проверьте правильность заполнения форм</div> 

      </div>
     
     <div class="onSuccess hide">
        <div class="messageSent">
     	    <img src="{% static 'contact/images/iconmonstr-paper-plane-5.svg' %}" alt="mail" width=70px>
         	<p>Сообщение успешно отправлено, <br> спасибо за обращение !</p>
        </div>
           <a class="button onmain" href="{% url 'home:home' %}">НА ГЛАВНУЮ</a>
      </div>   
	
	</div>
	
	
	
</div>
    

    
  </main>

   <footer>
    <img id="prefooter" src="{% static 'home/images/preGroup.png' %}">
    <div class="footer">
   <img id="footerimg" src="{% static 'home/images/Group.png' %}" alt="слайд" >
    <div class="footerRef">
       {% include "home/footerRef.html" %} 
     </div>
  </div>
   
  </footer>


   

</body>

</html>

contact/templates/contact/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
   <form method="POST">

   {% csrf_token %}
   <input type="email", name="email" value="em@em.em">

   
   <button type="submit">Submit</button>
  </form> 

</body>
</html>